Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "trusty64"
  c.vm.box_url = "trusty-server-cloudimg-amd64-vagrant-disk1.box"
  c.vm.hostname = "default-trusty64"
  c.vm.network(:private_network, {:ip=>"192.168.101.101"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "4192"]
  end
end
